GET http://localhost:3000/products

###
GET http://localhost:3000/products/3

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Shirt",
  "price": 10,
  "image_url": "",
  "description": "Wear this on top"
}