GET http://localhost:3000/products.json

###
GET http://localhost:3000/products/3.json

###
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "Coat",
  "price": 1,
  "image_url": "",
  "description": "Warm"
}

###
PATCH http://localhost:3000/products/12.json
Content-Type: application/json

{
  "image_url": "Picture of chair"
}

###
DELETE http://localhost:3000/products/5.json