@admin = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjA1OTY3MzR9.bduQNQKLK3D5ELux0A1tIp4b_ytFGywkcIS_nuaJWFo

@user_id2 = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NjA1OTA5NzZ9.RDeuDht9Kmh4ZZwZ3Z1xFhtSe491t6dfKo320hGZ91k 

@user_id3 = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NjA1OTEwMDF9.6DFtn5mvEPeFbb4yDobcqzU1rqxf6LEveOhdji7OIYQ

###Create a session/ user logs in
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "john@john.com",
  "password": "password"
}

### View All Orders of User
GET  http://localhost:3000/orders.json
Authorization: Bearer {{user_id3}}

### View an order (logged in)
GET http://localhost:3000/orders/2.json
Authorization: Bearer {{user_id3}}

### Create an order (BUY)
POST http://localhost:3000/orders.json
Authorization: Bearer {{user_id3}}

### Add item to Cart
POST http://localhost:3000/carted_products
Authorization: Bearer {{admin}}
Content-Type: application/json

{
  "product_id": 10,
  "quantity": 4
}

### View Carted_products
GET http://localhost:3000/carted_products.json
Authorization: Bearer {{admin}}

### Remove Item from Cart
DELETE  http://localhost:3000/carted_products/1
Authorization: Bearer {{admin}}

###View ALL products
GET http://localhost:3000/products.json